services:
  database:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=mysql
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
    ports:
      - 3306:3306 # MySQL default port
    networks:
      - default
    volumes:
      - mysql_data:/var/lib/mysql # Mount volume to persist data

volumes:
  mysql_data: # Renamed volume to match MySQL
